server:
  port: 8080

logging:
  level:
    org.springframework.cloud.gateway: DEBUG

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
#        - id: user-service
#          # forwards /users/** to user service
#          uri: http://localhost:8081
#          predicates:
#            - Path=/users/**

        - id: auth-service
          # forwards /api/auth/** to user service
          uri: http://localhost:8081
          predicates:
            - Path=/api/auth/**
          # Uncomment this if your user-service endpoint is /auth/** instead of /api/auth/**
          #filters:
          #  - StripPrefix=1

        - id: product-service
          # forwards /api/auth/** to user service
          uri: http://localhost:8082
          predicates:
            - Path=/api/products/**
